### ISSUE TITLE
tir.tir._TagNotFound: could not found HTML tag 'div' with attribute 'class' and value which should contain 'container top'

### ISSUE THREAD

**Issue by spilehchiha** [Pouriya-Jahanbakhsh/tir#3]
This error is raised while running the `tir` command:

Traceback (most recent call last):
  File "/usr/local/bin/tir", line 555, in <module>
    main()
  File "/usr/local/bin/tir", line 457, in main
    transformed = HTMLParser(data, transformers).parse()
  File "/usr/local/lib/python3.7/site-packages/tir-18.12.25-py3.7.egg/tir/tir.py", line 280, in parse
    transform_data[name] = transformer(self.html)
  File "/usr/local/bin/tir", line 84, in find_dates
    container_top = search(html.body, 'div', 'class', ('container top',))
  File "/usr/local/lib/python3.7/site-packages/tir-18.12.25-py3.7.egg/tir/tir.py", line 224, in search
    raise _TagNotFound(tag, attr, val)
tir.tir._TagNotFound: could not found HTML tag 'div' with attribute 'class' and value which should contain 'container top'

**Comment by Pouriya-Jahanbakhsh** [comment]
Thank you. something is changed in time.ir. I'm on it.

**Comment by spilehchiha** [comment]
I could help if you needed any.

Best Regards,
Sina Pilehchiha
sina.pilehchiha@mail.concordia.ca<mailto:sina.pilehchiha@mail.concordia.ca>

On May 12, 2019, at 3:07 PM, Pouriya <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you. something is changed in time.ir<http://time.ir>. I'm on it.

**Comment by Pouriya-Jahanbakhsh** [comment]
Fixed! test version [19.5.12](https://github.com/Pouriya-Jahanbakhsh/tir/tree/19.5.12). Thank you very much.
